# Script to build and publish a Reloaded Mod.
# by Sewer56

# Produces: 
#   - Build to Upload to GameBanana
#   - Build to Upload to GitHub
#   - Build to Upload to NuGet
#   - Changelog

# When pushing a tag
#   - Upload to GitHub Releases
#   - Upload to Reloaded NuGet Repository (if GitHub Secret RELOADED_NUGET_KEY is specified) 

name: Build and Publish Reloaded Mod

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

env:
  PUBLISH_BASE: ./Publish
  PUBLISH_GAMEBANANA_PATH: ToUpload/GameBanana
  PUBLISH_GITHUB_PATH: ToUpload/Generic
  PUBLISH_NUGET_PATH: ToUpload/NuGet

  PUBLISH_CHANGELOG_PATH: CHANGELOG.md

  RELOADEDIIMODS: .
  RELOADED_TOOLS_PATH: Tools/Reloaded-Tools

  # Default value is official Reloaded package server.  
  RELOADED_NUGET_URL: https://packages.sewer56.moe/v3/index.json

  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup .NET Core 5.0 # For Reloaded Publisher
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 9.0 # For C# parts of mod
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 9.0.x

    - name: Setup Rust Nightly # For Rust parts of mod
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        components: rust-src
        target: x86_64-pc-windows-msvc